### ISSUE TITLE
I have bug with doom-buffer-mode and icons neotree

### ISSUE THREAD

**Issue by gangashman** [hlissner/emacs-doom-theme#39]
I have two bugs or I use something wrong.

First with this part: when I move between my frames, "doom-buffer-mode" is not change.
```
  ;; brighter source buffers
  (add-hook 'find-file-hook 'doom-buffer-mode)
  ;; brighter minibuffer when active
  (add-hook 'minibuffer-setup-hook 'doom-brighten-minibuffer)
  ;; The temporary buffers ediff spins up aren't dimmed. You can fix this with:
  (add-hook 'ediff-prepare-buffer-hook 'doom-buffer-mode)
```

Second with neotree: something's wrong with the icons:
![12](https://cloud.githubusercontent.com/assets/7021713/23106709/741163a8-f702-11e6-8317-76aaf02bad4c.png)

**Comment by hlissner** [comment]
About neotree:

Have you installed [the fonts provided by all-the-icons](https://github.com/domtronn/all-the-icons.el)? This is required to use their icons.

About doom-buffer-mode, that is strange. Could you provide a list of steps to reproduce that?

**Comment by gangashman** [comment]
> Have you installed the fonts provided by all-the-icons? This is required to use their icons.

Yes, but I have symbols instead icons, its not important because its most likely all-the-icons issue.

![screenshot_20170221_190501](https://cloud.githubusercontent.com/assets/7021713/23173303/d18ab648-f869-11e6-81d1-1f091ecef3cd.png)


> About doom-buffer-mode, that is strange. Could you provide a list of steps to reproduce that?

doom-buffer-mode work well if I use it trough M-x. New created buffers created with doom-buffer-mode (not always), darker than others, but when i switch between buffers nothing changes.

This is my settings:
```
(use-package doom-themes
  :ensure t
  :config
  (setq doom-neotree-enable-file-icons t)
  (load-theme 'doom-one t) ;; or doom-dark, etc.
  (setq doom-enable-bold t    ; if nil, bolding are universally disabled
	doom-enable-italic t  ; if nil, italics are universally disabled

	doom-one-brighter-modeline nil
	doom-one-brighter-comments nil
	)
  ;; brighter source buffers
  (add-hook 'find-file-hook 'doom-buffer-mode)
  ;; brighter minibuffer when active
  (add-hook 'minibuffer-setup-hook 'doom-brighten-minibuffer)
  ;; The temporary buffers ediff spins up aren't dimmed. You can fix this with:
  (add-hook 'ediff-prepare-buffer-hook 'doom-buffer-mode)
  
  ;; Enable custom neotree theme
  (require 'doom-neotree)    ; all-the-icons fonts must be installed!
  ;; Enable nlinum line highlighting
  (require 'doom-nlinum)     ; requires nlinum and hl-line-mode
  )
```

**Comment by hlissner** [comment]
This is strange. It is possible that an error is occuring before doom-buffer-mode gets run. You may want to check `view-echo-area-messages` to see if there are any error messages.

If there aren't any, here is a rather an alternative solution that works for me:

```emacs-lisp
  (defun doom*brighter-buffer-maybe (buffer &rest _)
    (when (and (not (bound-and-true-p doom-buffer-mode))
               buffer-file-name
               (not (doom-popup-p (selected-window))))
      (doom-buffer-mode +1)))
  (advice-add 'switch-to-buffer :after 'doom*brighter-buffer-maybe)
  (advice-add 'display-buffer   :after 'doom*brighter-buffer-maybe)
```

You do **not** need `(add-hook 'find-file-hook 'doom-buffer-mode)` with this.

Let me know if that solves your problem.

----

As for neotree, I don't think it's a neotree issue. I am using doom-themes neotree mod (on Arch Linux) and it works fine. From the screenshot, it looks like it's not recognizing the fonts.

**Comment by hlissner** [comment]
Whoops, ignore that `doom-popup-p` call in the above code. That's only for my emacs.d. I've corrected it now.

**Comment by gangashman** [comment]
Nothing changes with `doom*brighter-buffer-maybe`. Nothing in *Messages* buffer.

Its strange, because `doom-buffer-mode` work as well trough `M-c`, but `(add-hook 'find-file-hook 'doom-buffer-mode)` doesn't work at all. How can I test `add-hook 'find-file-hook`? I don't know how to use elisp.

**Comment by gangashman** [comment]
I tried on computer and on my laptop. Both are use Kubuntu, the result is the same.I tried to leave only the doom-themes settings in .emacs, it still doesn't work. Any clues?
