### ISSUE TITLE
org-hide-leading-stars not working after update

### ISSUE THREAD

**Issue by thorstengrothe** [hlissner/emacs-doom-theme#50]
Hi,

I got this in m .emacs.d
`setq org-hide-leading-stars t `

With version 20170316.1237 from melpa it works fine after the last update it look like this

![orgbug](https://cloud.githubusercontent.com/assets/19598706/25324598/fb9f3cdc-28c6-11e7-9fe5-9f09bcdd1ada.png)

Do you have an idea?

Thorsten

**Comment by hlissner** [comment]
This was caused by `doom-buffer-mode`. I've reverted the last update, but I'm confused: I see you're using a light theme. If you are switching themes (between a doom theme and a non-doom-theme), then `doom-buffer-mode` will overwrite that theme's org-hide face. 

I'll include some checks in a future fix to ensure that doesn't happen.

**Comment by thorstengrothe** [comment]
Ah thank you, after the last melpa update it seems to work. The light theme is only for viewing mails because with doom theme enabled they look like this (see the black font inline), btw. text mails are fine it's only with some (not all) html mails, I don't know why. With other dark themes it's the same...

![mu4e](https://cloud.githubusercontent.com/assets/19598706/25579712/613b46e0-2e7a-11e7-9d30-13e826833a39.png)

**Comment by hlissner** [comment]
My hunch is, in the email's HTML, the text is colored black, which Emacs translates into black text.

I realize this is unrelated to the issue here, but would you mind running this function while your point is on the black text?

```emacs-lisp
(defun what-face (pos)
  "Tells you the name of the face (point) is on."
  (interactive "d")
  (let ((hl-line-p (bound-and-true-p hl-line-mode)))
    (if hl-line-p (hl-line-mode -1))
    (let ((face (or (get-char-property (point) 'read-face-name)
                    (get-char-property (point) 'face))))
      (if face (message "Face: %s" face) (message "No face at %d" pos)))
    (if hl-line-p (hl-line-mode 1))))
```

That should tell me if there's anything I can do about it on doom-themes' end.

**Comment by thorstengrothe** [comment]
Of course, thanks for the help, this is the output

```
Invalid face reference: nil [67 times]
Face: (variable-pitch (:foreground #000000) mu4e-view-body-face)
Invalid face reference: nil [10 times]
QuitInvalid face reference: nil
Invalid face reference: nil [5 times]
```

**Comment by hlissner** [comment]
I think I know what the problem is. If you're using a version of Emacs older than 25.0, then mu4e may be using the older `html2text` package to render html. It's not intelligent about color collisions with your active Emacs theme.

Newer versions of Emacs has the `shr` library (built-in) to render HTML, which has a fix for this issue.

If you check the variable `mu4e-html2text-command`, and if it contains `html2text`, then my hunch is correct and the only way to fix it is to upgrade Emacs. 

Unfortunately, I don't know in what version of Emacs `shr` was introduced, but I haven't had an issue with dark text on dark backgrounds since 25.0 (and am now using 25.2), so I assume v25+ is safe.

**Comment by hlissner** [comment]
Anyhow, I've fixed the original issue (with org-hide), so I'll close this issue. Feel free to email me (address is in [my profile](https://github.com/hlissner)) to follow up on the email problem, if you'd like.

**Comment by amosbird** [comment]
Hi, when `solaire-mode` is on, doom still doesn't hide leading stars in terminal mode.

![image](https://user-images.githubusercontent.com/5085485/31319520-4e779e2c-ac2a-11e7-94cc-632ad01d7ebf.png)

**Comment by hlissner** [comment]
@amosbird Just pushed a possible fix for that. Please check it out and let me know if it resolves your issue.

**Comment by amosbird** [comment]
@hlissner Thanks! Hmm, how can I use this in doom-emacs?

**Comment by hlissner** [comment]
@amosbird Run `make update` to update Doom's plugins, including this one. Then restart Emacs and you should see the changes.

**Comment by amosbird** [comment]
Ah, it works fine now. Thanks!
