### ISSUE TITLE
jdee-mode some colours are off

### ISSUE THREAD

**Issue by gicmo** [hlissner/emacs-doom-theme#52]
Hey,

some colours, .e.g the link, breakpoint (bright green line) seem off in [jdee-mode](https://github.com/jdee-emacs/jdee/blob/master/jdee-font-lock.el); see below.

<img width="798" alt="emacs-jdee-colors" src="https://cloud.githubusercontent.com/assets/2040/25739740/7da53fdc-3183-11e7-86e6-0f1dbe5c450b.png">

**Comment by hlissner** [comment]
I've added jdee faces and fixed the link (among other things), but I couldn't find the face for the breakpoint. Do you know what face that is? If you don't, place your cursor over it and run the following:

```emacs-lisp
(or (get-char-property (point) 'read-face-name)
    (get-char-property (point) 'face))
```

It should tell you what face is applied there (turn off `hl-line-mode` first, if you use it). That should tell me where to look.

**Comment by gicmo** [comment]
Thanks a lot! It seems to be `jdee-db-spec-breakpoint-face`.

**Comment by hlissner** [comment]
Alright, round two. That should fix the breakpoints, hopefully. The way jdee initializes its breakpoint faces is a little... strange, so please test it and let me know if it worked.

**Comment by gicmo** [comment]
I am afraid the breakpoint changes broke the whole mode, I get `File mode specification error: (invalid-function #1B2229)`. Commenting out the three jdee-db unbreaks it.

**Comment by hlissner** [comment]
My bad, this revealed an unrelated issue with `doom-common-variables` as the cause. It should be fixed now.

**Comment by gicmo** [comment]
I am still getting the `File mode specification error: (invalid-function #1B2229)` error.

```lisp
Debugger entered--Lisp error: (invalid-function "#1B2229")
  ("#1B2229" . "#3B3F46")
  eval(("#1B2229" . "#3B3F46"))
  custom-initialize-reset(jdee-db-spec-breakpoint-face-colors (cons "black" "green"))
  custom-declare-variable(jdee-db-spec-breakpoint-face-colors (cons "black" "green") "*Specifies the foreground and background colors used to highlight\nthe line at which you have specified that a breakpoint to be set." :group jdee-project :type (cons :tag "Colors" (string :tag "Foreground") (string :tag "Background")) :set (lambda (sym val) (make-face (quote jdee-db-spec-breakpoint-face)) (set-face-foreground (quote jdee-db-spec-breakpoint-face) (car val)) (set-face-background (quote jdee-db-spec-breakpoint-face) (cdr val)) (set-default sym val)))
  byte-code("[...]" [custom-declare-variable jdee-db-spec-breakpoint-face-colors (cons "black" "green") "*Specifies the foreground and background colors used to highlight\nthe line at which you have specified that a breakpoint to be set." :group jdee-project :type (cons :tag "Colors" (string :tag "Foreground") (string :tag "Background")) :set (lambda (sym val) (make-face (quote jdee-db-spec-breakpoint-face)) (set-face-foreground (quote jdee-db-spec-breakpoint-face) (car val)) (set-face-background (quote jdee-db-spec-breakpoint-face) (cdr val)) (set-default sym val)) jdee-db-requested-breakpoint-face-colors (cons "black" "yellow") "*Specifies the foreground and background colors used to highlight\nthe line at which you have requested a breakpoint to be set." (cons :tag "Colors" (string :tag "Foreground") (string :tag "Background")) (lambda (sym val) (make-face (quote jdee-db-requested-breakpoint-face)) (set-face-foreground (quote jdee-db-requested-breakpoint-face) (car val)) (set-face-background (quote jdee-db-requested-breakpoint-face) (cdr val)) (set-default sym val)) jdee-db-active-breakpoint-face-colors (cons "black" "red") "*Specifies the foreground and background colors used to highlight\na line where an active breakpoint exists." (cons :tag "Colors" (string :tag "Foreground") (string :tag "Background")) (lambda (sym val) (make-face (quote jdee-db-active-breakpoint-face)) (set-face-foreground (quote jdee-db-active-breakpoint-face) (car val)) (set-face-background (quote jdee-db-active-breakpoint-face) (cdr val)) (set-default sym val)) defalias jdee-db-breakpoint-marker-p eieio-make-class-predicate jdee-db-breakpoint-marker jdee-db-breakpoint-marker--eieio-childp eieio-make-child-predicate jdee-db-breakpoint-marker-child-p make-obsolete "use (cl-typep ... 'jdee-db-breakpoint-marker) instead" "25.1" put cl-deftype-satisfies eieio-defclass-internal nil ((marker :initarg :marker :documentation "Overlay in Emacs, extent in XEmacs")) (:documentation "Indicates the location of breakpoints in a source buffer. This class\nuses overlays as markers in Emacs and extents in XEmacs.")] 10)
  require(jdee-db)
  byte-code([...]" [require cl-lib eieio jdee-classpath jdee-db jdee-dbo jdee-files tree-widget custom-declare-variable jdee-bug-sio-connect-delay 1 "Length of time in seconds that the JDE waits\nbefore attempting to connect to the\ndebuggee application's standard I/O. This delay\nis intended to give JDEbug time to create the\nSIO socket. Try increasing this variable if JDEbug\nhangs while launching an application. If your\nsystem never hangs, you can reduce this setting\nto 0 to eliminate the connection delay." :group jdee-bug :type integer] 8)
  require(jdee-dbs)
  byte-code("[...]" [require cl-lib jdee-files jdee-parse jdee-dbs jdee-dbo jdee-db jdee-run efc semantic/util-modes custom-declare-group jdee-bug nil "JDEbug General Options" :group jdee :prefix "jdee-bug" custom-declare-variable jdee-bug-debug "*IMPORTANT!!!! Leave this switch in its default state (off) unless\nyou need to modify the *JDEbug* Java source code. Setting this switch\non causes the JDE to load *JDEbug* from its java/classes directory\ninstead of from jde.jar. It also causes the JDE to run the debugger in\ndebug server mode. This allows you to use *JDEbug* to debug itself." :type boolean jdee-bug-jpda-directory "" "*Pathname of the directory containing Sun's Java Platform Debug Architecture\ndistribution. You need to set this variable only if this project uses a JDK 1.2 vm." file] 8)
  require(jdee-bug)
  byte-code("[...]" [require browse-url cc-defs cc-mode cedet cl-lib comint compile cus-edit easymenu executable jdee-log jdee-activator jdee-classpath jdee-abbrev jdee-annotations jdee-bug jdee-class jdee-compile jdee-complete jdee-custom jdee-cygwin jdee-db jdee-deps jdee-find jdee-gen jdee-help jdee-import jdee-issues jdee-font-lock jdee-java-grammar jdee-jdb jdee-jdk-manager jdee-keys jdee-open-source jdee-project-file jdee-refactor jdee-run jdee-stacktrace jdee-archive jdee-test jdee-util jdee-which-method jdee-wiz semantic thingatpt] 2)
  jdee-mode()
  set-auto-mode-0(jdee-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer File.java> "~/.../File.java" nil nil "~/.../File.java" (731738 16777227))
  find-file-noselect(".../File.java" nil nil nil)
  find-file(".../File.java")
```

**Comment by hlissner** [comment]
Alright, pushed another fix! Let me know if it does the trick.

**Comment by gicmo** [comment]
That seems to have done the trick. Many thanks!
